// See https://aka.ms/new-console-template for more information
Console.WriteLine("--PET SHOP CHECK-IN--");
Console.Write("Especie:....");
string Especie = Console.ReadLine()!;
Console.Write("Raça:......");
string Raça = Console.ReadLine()!;
Console.Write("Alcunha:....");
string Alcunha= Console.ReadLine()!;
Console.Write("Idade:....");
string Idade = Console.ReadLine()!;
Console.Write("Cor/Pelagem:....");
string CorPelagem = Console.ReadLine()!;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.Yellow;
Console.WriteLine("+=========================================================+");
Console.Write("|                 ");
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("Pet Hotel-- Alegria do Pet");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("                  |");
Console.Write("| Especie: ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write(Especie);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write(" | Raça:");
Console.Write (Raça);
Console.ForegroundColor = ConsoleColor.Blue;
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine(" |");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("+=========================================================+");
Console.Write("| Atende pela alcunha de: ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write (Alcunha);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine(" |");
Console.Write("| Idade: ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write(Idade);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write(" | Pelagem/cor: ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write(CorPelagem);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine(" |");

Console.ForegroundColor = ConsoleColor.Yellow ;
Console.Write("+=========================================================+");

Console.ResetColor();
